import { ThemeConfig } from '@/types';

export const themes: Record<string, ThemeConfig> = {
  default: {
    name: '默认主题',
    description: '经典蓝色主题，适合日常使用',
    mood: '日常',
    colors: {
      primary: '#007bff',
      primaryHover: '#0056b3',
      secondary: '#6c757d',
      success: '#28a745',
      danger: '#dc3545',
      warning: '#ffc107',
      info: '#17a2b8',
      light: '#f8f9fa',
      dark: '#343a40',
      textPrimary: '#333',
      textSecondary: '#666',
      textMuted: '#999',
      backgroundLight: '#f8f9fa',
      backgroundDark: '#ffffff',
      borderColor: '#ddd',
      shadowColor: 'rgba(0, 0, 0, 0.1)',
    },
  },
  sunny: {
    name: '阳光主题',
    description: '温暖的橙色系，带来好心情',
    mood: '开心',
    colors: {
      primary: '#ff6b35',
      primaryHover: '#e55a2b',
      secondary: '#ffa726',
      success: '#66bb6a',
      danger: '#ef5350',
      warning: '#ffb74d',
      info: '#42a5f5',
      light: '#fff3e0',
      dark: '#e65100',
      textPrimary: '#2e2e2e',
      textSecondary: '#666',
      textMuted: '#999',
      backgroundLight: '#fff8e1',
      backgroundDark: '#ffffff',
      borderColor: '#ffcc80',
      shadowColor: 'rgba(255, 107, 53, 0.15)',
    },
  },
  calm: {
    name: '宁静主题',
    description: '柔和的绿色系，让人心情平静',
    mood: '平静',
    colors: {
      primary: '#4caf50',
      primaryHover: '#388e3c',
      secondary: '#81c784',
      success: '#66bb6a',
      danger: '#ef5350',
      warning: '#ffb74d',
      info: '#42a5f5',
      light: '#e8f5e8',
      dark: '#2e7d32',
      textPrimary: '#2e2e2e',
      textSecondary: '#666',
      textMuted: '#999',
      backgroundLight: '#f1f8e9',
      backgroundDark: '#ffffff',
      borderColor: '#a5d6a7',
      shadowColor: 'rgba(76, 175, 80, 0.15)',
    },
  },
  energetic: {
    name: '活力主题',
    description: '充满活力的紫色系，激发创造力',
    mood: '兴奋',
    colors: {
      primary: '#9c27b0',
      primaryHover: '#7b1fa2',
      secondary: '#ba68c8',
      success: '#66bb6a',
      danger: '#ef5350',
      warning: '#ffb74d',
      info: '#42a5f5',
      light: '#f3e5f5',
      dark: '#6a1b9a',
      textPrimary: '#2e2e2e',
      textSecondary: '#666',
      textMuted: '#999',
      backgroundLight: '#faf5ff',
      backgroundDark: '#ffffff',
      borderColor: '#ce93d8',
      shadowColor: 'rgba(156, 39, 176, 0.15)',
    },
  },
  cozy: {
    name: '温馨主题',
    description: '温暖的棕色系，营造家的感觉',
    mood: '温馨',
    colors: {
      primary: '#8d6e63',
      primaryHover: '#6d4c41',
      secondary: '#a1887f',
      success: '#66bb6a',
      danger: '#ef5350',
      warning: '#ffb74d',
      info: '#42a5f5',
      light: '#efebe9',
      dark: '#4e342e',
      textPrimary: '#3e2723',
      textSecondary: '#666',
      textMuted: '#999',
      backgroundLight: '#faf7f5',
      backgroundDark: '#ffffff',
      borderColor: '#bcaaa4',
      shadowColor: 'rgba(141, 110, 99, 0.15)',
    },
  },
  professional: {
    name: '专业主题',
    description: '深色系主题，适合工作环境',
    mood: '专注',
    colors: {
      primary: '#2c3e50',
      primaryHover: '#1a252f',
      secondary: '#34495e',
      success: '#27ae60',
      danger: '#e74c3c',
      warning: '#f39c12',
      info: '#3498db',
      light: '#ecf0f1',
      dark: '#2c3e50',
      textPrimary: '#2c3e50',
      textSecondary: '#7f8c8d',
      textMuted: '#bdc3c7',
      backgroundLight: '#f8f9fa',
      backgroundDark: '#ffffff',
      borderColor: '#bdc3c7',
      shadowColor: 'rgba(44, 62, 80, 0.15)',
    },
  },
  day: {
    name: '白天主题',
    description: '明亮清新的日间主题，适合白天使用',
    mood: '清新',
    colors: {
      primary: '#2196f3',
      primaryHover: '#1976d2',
      secondary: '#64b5f6',
      success: '#4caf50',
      danger: '#f44336',
      warning: '#ff9800',
      info: '#00bcd4',
      light: '#e3f2fd',
      dark: '#1565c0',
      textPrimary: '#212121',
      textSecondary: '#757575',
      textMuted: '#9e9e9e',
      backgroundLight: '#fafafa',
      backgroundDark: '#ffffff',
      borderColor: '#e0e0e0',
      shadowColor: 'rgba(33, 150, 243, 0.15)',
    },
  },
  night: {
    name: '夜间主题',
    description: '深色护眼主题，适合夜间使用',
    mood: '舒适',
    colors: {
      primary: '#bb86fc',
      primaryHover: '#a66ffc',
      secondary: '#03dac6',
      success: '#00e676',
      danger: '#cf6679',
      warning: '#ffb74d',
      info: '#42a5f5',
      light: '#0a0a0a',
      dark: '#121212',
      textPrimary: '#ffffff',
      textSecondary: '#b3b3b3',
      textMuted: '#808080',
      backgroundLight: '#0a0a0a',
      backgroundDark: '#1e1e1e',
      borderColor: '#0a0a0a',
      shadowColor: 'rgba(0, 0, 0, 0.3)',
    },
  },
};

export const defaultTheme = 'default'; 