# Sample workflow for building and deploying a React + Vite site to GitHub Pages
name: Deploy React + Vite to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'  # 保持你的 Node 版本
          cache: 'npm'  # 保留缓存加速安装，但确保依赖正确
        
      - name: Clean existing dependencies
        run: |
          rm -rf node_modules package-lock.json yarn.lock
          npm cache clean --force
          
      - name: Install dependencies (including optional)
        run: npm install  # 移除 --no-optional 和 --ignore-scripts，确保可选依赖被安装
          
      - name: Generate articles
        run: npm run generate-articles
        
      - name: Build with Vite
        env:
          NODE_ENV: production
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4